theme: jekyll-theme-primer
title: CS109 Final Project (Group 48)
description: CS109 Final Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
