theme: jekyll-theme-primer
title: Machine Learning & Analysis for Twitter Bot Detection
description: Machine Learning & Analysis for Twitter Bot Detection
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
